### ISSUE TITLE
SlugRelatedField gets put into links

### ISSUE THREAD

**Issue by webjunkie** [Artory/drf-hal-json#22]
SlugRelatedField is never a http link, so it might not be useful to end up there.

**Comment by claytondaley** [comment]
Note that it *could* be a link.  Imagine a bank that has a service endpoint for accounts and a service endpoint for users (for the sake of argument, written in different languages).  Obviously, there needs to be a link between users and accounts.  Since the user side doesn't know how to build an account URI from scratch, it could store (and serve) these URIs out of a table that was basically `(id, user, uri)`.  A `SlugRelatedField` would be one (and I think the best practice) way to access this field.

However, this seems like a special case that should be addressed by a special case class (or some other technique).
